/* Generated by scriptc from /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts. Do not edit. */
#include "scr_runtime.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

static struct { size_t rc; size_t len; size_t cap; char data[8]; } sc_lit_0 =
    { SIZE_MAX, 7, 7, "running" };
static struct { size_t rc; size_t len; size_t cap; char data[26]; } sc_lit_1 =
    { SIZE_MAX, 25, 25, "running\357\274\232\346\266\210\346\201\257\345\217\221\351\200\201\344\270\255" };
static struct { size_t rc; size_t len; size_t cap; char data[6]; } sc_lit_2 =
    { SIZE_MAX, 5, 5, "empty" };
static struct { size_t rc; size_t len; size_t cap; char data[12]; } sc_lit_3 =
    { SIZE_MAX, 11, 11, "compactable" };
static struct { size_t rc; size_t len; size_t cap; char data[7]; } sc_lit_4 =
    { SIZE_MAX, 6, 6, "active" };
static struct { size_t rc; size_t len; size_t cap; char data[7]; } sc_lit_5 =
    { SIZE_MAX, 6, 6, "latest" };
static struct { size_t rc; size_t len; size_t cap; char data[10]; } sc_lit_6 =
    { SIZE_MAX, 9, 9, "completed" };
static struct { size_t rc; size_t len; size_t cap; char data[28]; } sc_lit_7 =
    { SIZE_MAX, 27, 27, "completed\357\274\232\346\266\210\346\201\257\345\267\262\345\256\214\346\210\220" };
static struct { size_t rc; size_t len; size_t cap; char data[15]; } sc_lit_8 =
    { SIZE_MAX, 14, 14, "goal-verifying" };
static struct { size_t rc; size_t len; size_t cap; char data[31]; } sc_lit_9 =
    { SIZE_MAX, 30, 30, "goalVerifying\357\274\232goal \351\252\214\350\257\201\344\270\255" };
static struct { size_t rc; size_t len; size_t cap; char data[14]; } sc_lit_10 =
    { SIZE_MAX, 13, 13, "goalVerifying" };
static struct { size_t rc; size_t len; size_t cap; char data[10]; } sc_lit_11 =
    { SIZE_MAX, 9, 9, "verifying" };
static struct { size_t rc; size_t len; size_t cap; char data[11]; } sc_lit_12 =
    { SIZE_MAX, 10, 10, "compacting" };
static struct { size_t rc; size_t len; size_t cap; char data[28]; } sc_lit_13 =
    { SIZE_MAX, 27, 27, "compacting\357\274\232\346\255\243\345\234\250 compact" };
static struct { size_t rc; size_t len; size_t cap; char data[20]; } sc_lit_14 =
    { SIZE_MAX, 19, 19, "just-compacted-noop" };
static struct { size_t rc; size_t len; size_t cap; char data[53]; } sc_lit_15 =
    { SIZE_MAX, 52, 52, "justCompacted\357\274\232\345\210\232\345\216\213\347\274\251\345\256\214\357\274\214\344\270\215\351\234\200\350\246\201\347\273\247\347\273\255\345\216\213\347\274\251" };
static struct { size_t rc; size_t len; size_t cap; char data[14]; } sc_lit_16 =
    { SIZE_MAX, 13, 13, "justCompacted" };
static struct { size_t rc; size_t len; size_t cap; char data[20]; } sc_lit_17 =
    { SIZE_MAX, 19, 19, "just-compacted-more" };
static struct { size_t rc; size_t len; size_t cap; char data[53]; } sc_lit_18 =
    { SIZE_MAX, 52, 52, "justCompacted\357\274\232\345\210\232\345\216\213\347\274\251\345\256\214\357\274\214\344\275\206\350\277\230\350\203\275\347\273\247\347\273\255\345\216\213\347\274\251" };
static struct { size_t rc; size_t len; size_t cap; char data[9]; } sc_lit_19 =
    { SIZE_MAX, 8, 8, "sendText" };
static struct { size_t rc; size_t len; size_t cap; char data[5]; } sc_lit_20 =
    { SIZE_MAX, 4, 4, "user" };
static struct { size_t rc; size_t len; size_t cap; char data[19]; } sc_lit_21 =
    { SIZE_MAX, 18, 18, "\347\273\247\347\273\255\345\217\221\351\200\201\346\226\207\345\255\227" };
static struct { size_t rc; size_t len; size_t cap; char data[5]; } sc_lit_22 =
    { SIZE_MAX, 4, 4, "none" };
static struct { size_t rc; size_t len; size_t cap; char data[9]; } sc_lit_23 =
    { SIZE_MAX, 8, 8, "composer" };
static struct { size_t rc; size_t len; size_t cap; char data[13]; } sc_lit_24 =
    { SIZE_MAX, 12, 12, "slashCompact" };
static struct { size_t rc; size_t len; size_t cap; char data[16]; } sc_lit_25 =
    { SIZE_MAX, 15, 15, "\350\276\223\345\205\245 /compact" };
static struct { size_t rc; size_t len; size_t cap; char data[8]; } sc_lit_26 =
    { SIZE_MAX, 7, 7, "setGoal" };
static struct { size_t rc; size_t len; size_t cap; char data[12]; } sc_lit_27 =
    { SIZE_MAX, 11, 11, "\350\256\276\347\275\256 goal" };
static struct { size_t rc; size_t len; size_t cap; char data[13]; } sc_lit_28 =
    { SIZE_MAX, 12, 12, "goal control" };
static struct { size_t rc; size_t len; size_t cap; char data[8]; } sc_lit_29 =
    { SIZE_MAX, 7, 7, "compact" };
static struct { size_t rc; size_t len; size_t cap; char data[15]; } sc_lit_30 =
    { SIZE_MAX, 14, 14, "\347\202\271\345\207\273 compact" };
static struct { size_t rc; size_t len; size_t cap; char data[8]; } sc_lit_31 =
    { SIZE_MAX, 7, 7, "toolbar" };
static struct { size_t rc; size_t len; size_t cap; char data[11]; } sc_lit_32 =
    { SIZE_MAX, 10, 10, "forkLatest" };
static struct { size_t rc; size_t len; size_t cap; char data[18]; } sc_lit_33 =
    { SIZE_MAX, 17, 17, "fork \346\234\200\346\226\260\350\275\256\346\254\241" };
static struct { size_t rc; size_t len; size_t cap; char data[13]; } sc_lit_34 =
    { SIZE_MAX, 12, 12, "turn actions" };
static struct { size_t rc; size_t len; size_t cap; char data[8]; } sc_lit_35 =
    { SIZE_MAX, 7, 7, "forkOld" };
static struct { size_t rc; size_t len; size_t cap; char data[15]; } sc_lit_36 =
    { SIZE_MAX, 14, 14, "fork \350\200\201\350\275\256\346\254\241" };
static struct { size_t rc; size_t len; size_t cap; char data[4]; } sc_lit_37 =
    { SIZE_MAX, 3, 3, "old" };
static struct { size_t rc; size_t len; size_t cap; char data[11]; } sc_lit_38 =
    { SIZE_MAX, 10, 10, "editLatest" };
static struct { size_t rc; size_t len; size_t cap; char data[19]; } sc_lit_39 =
    { SIZE_MAX, 18, 18, "\347\274\226\350\276\221\346\234\200\346\226\260 query" };
static struct { size_t rc; size_t len; size_t cap; char data[16]; } sc_lit_40 =
    { SIZE_MAX, 15, 15, "message actions" };
static struct { size_t rc; size_t len; size_t cap; char data[8]; } sc_lit_41 =
    { SIZE_MAX, 7, 7, "editOld" };
static struct { size_t rc; size_t len; size_t cap; char data[16]; } sc_lit_42 =
    { SIZE_MAX, 15, 15, "\347\274\226\350\276\221\350\200\201 query" };
static struct { size_t rc; size_t len; size_t cap; char data[18]; } sc_lit_43 =
    { SIZE_MAX, 17, 17, "assistantComplete" };
static struct { size_t rc; size_t len; size_t cap; char data[7]; } sc_lit_44 =
    { SIZE_MAX, 6, 6, "system" };
static struct { size_t rc; size_t len; size_t cap; char data[27]; } sc_lit_45 =
    { SIZE_MAX, 26, 26, "assistant \345\256\214\346\210\220\345\275\223\345\211\215 run" };
static struct { size_t rc; size_t len; size_t cap; char data[14]; } sc_lit_46 =
    { SIZE_MAX, 13, 13, "runtime event" };
static struct { size_t rc; size_t len; size_t cap; char data[16]; } sc_lit_47 =
    { SIZE_MAX, 15, 15, "compactComplete" };
static struct { size_t rc; size_t len; size_t cap; char data[15]; } sc_lit_48 =
    { SIZE_MAX, 14, 14, "compact \345\256\214\346\210\220" };
static struct { size_t rc; size_t len; size_t cap; char data[12]; } sc_lit_49 =
    { SIZE_MAX, 11, 11, "compactNoop" };
static struct { size_t rc; size_t len; size_t cap; char data[30]; } sc_lit_50 =
    { SIZE_MAX, 29, 29, "compact \345\210\244\346\226\255\344\270\215\351\234\200\350\246\201\347\273\247\347\273\255" };
static struct { size_t rc; size_t len; size_t cap; char data[16]; } sc_lit_51 =
    { SIZE_MAX, 15, 15, "goalVerifyStart" };
static struct { size_t rc; size_t len; size_t cap; char data[19]; } sc_lit_52 =
    { SIZE_MAX, 18, 18, "\345\274\200\345\247\213 goal \351\252\214\350\257\201" };
static struct { size_t rc; size_t len; size_t cap; char data[13]; } sc_lit_53 =
    { SIZE_MAX, 12, 12, "goal runtime" };
static struct { size_t rc; size_t len; size_t cap; char data[15]; } sc_lit_54 =
    { SIZE_MAX, 14, 14, "goalVerifyPass" };
static struct { size_t rc; size_t len; size_t cap; char data[18]; } sc_lit_55 =
    { SIZE_MAX, 17, 17, "goal \351\252\214\350\257\201\351\200\232\350\277\207" };
static struct { size_t rc; size_t len; size_t cap; char data[15]; } sc_lit_56 =
    { SIZE_MAX, 14, 14, "goalVerifyFail" };
static struct { size_t rc; size_t len; size_t cap; char data[18]; } sc_lit_57 =
    { SIZE_MAX, 17, 17, "goal \351\252\214\350\257\201\345\244\261\350\264\245" };

typedef struct sc_rs_r0 sc_rs_r0; /* record r0 { canCompactAgain; compactMemory; forked; goal; queue; runPhase; selectedTurn } */
typedef struct sc_rs_r1 sc_rs_r1; /* record r1 { id; kind; label; surface; target } */
typedef struct sc_rs_r6 sc_rs_r6; /* record r6 { context; id; label } */

struct sc_rs_r0 { /* record r0 { canCompactAgain; compactMemory; forked; goal; queue; runPhase; selectedTurn } */
  size_t rc;
  bool sc_fld_canCompactAgain; /* canCompactAgain */
  ScrStr *sc_fld_compactMemory; /* compactMemory */
  bool sc_fld_forked; /* forked */
  ScrStr *sc_fld_goal; /* goal */
  ScrStr *sc_fld_queue; /* queue */
  ScrStr *sc_fld_runPhase; /* runPhase */
  ScrStr *sc_fld_selectedTurn; /* selectedTurn */
};
struct sc_rs_r1 { /* record r1 { id; kind; label; surface; target } */
  size_t rc;
  ScrStr *sc_fld_id; /* id */
  ScrStr *sc_fld_kind; /* kind */
  ScrStr *sc_fld_label; /* label */
  ScrStr *sc_fld_surface; /* surface */
  ScrStr *sc_fld_target; /* target */
};
struct sc_rs_r6 { /* record r6 { context; id; label } */
  size_t rc;
  sc_rs_r0 *sc_fld_context; /* context */
  ScrStr *sc_fld_id; /* id */
  ScrStr *sc_fld_label; /* label */
};

static sc_rs_r0 *sc_rretain_r0(sc_rs_r0 *o);
static void sc_rrelease_r0(sc_rs_r0 *o);
static sc_rs_r0 *sc_rnew_r0(void);
static sc_rs_r1 *sc_rretain_r1(sc_rs_r1 *o);
static void sc_rrelease_r1(sc_rs_r1 *o);
static sc_rs_r1 *sc_rnew_r1(void);
static sc_rs_r6 *sc_rretain_r6(sc_rs_r6 *o);
static void sc_rrelease_r6(sc_rs_r6 *o);
static sc_rs_r6 *sc_rnew_r6(void);

static sc_rs_r0 *sc_rretain_r0(sc_rs_r0 *o) {
  if (o && o->rc != SIZE_MAX) o->rc++;
  return o;
}
static void sc_rrelease_r0(sc_rs_r0 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    if (o->sc_fld_compactMemory) scr_str_release(o->sc_fld_compactMemory);
    if (o->sc_fld_goal) scr_str_release(o->sc_fld_goal);
    if (o->sc_fld_queue) scr_str_release(o->sc_fld_queue);
    if (o->sc_fld_runPhase) scr_str_release(o->sc_fld_runPhase);
    if (o->sc_fld_selectedTurn) scr_str_release(o->sc_fld_selectedTurn);
    scr_obj_free_note();
    free(o);
  }
}
static sc_rs_r0 *sc_rnew_r0(void) {
  sc_rs_r0 *o = calloc(1, sizeof *o);
  if (!o) { scr_trap("scriptc: out of memory\n"); }
  o->rc = 1;
  scr_obj_alloc_note();
  return o;
}
static void *sc_rretain_r0_v(void *o) { return sc_rretain_r0((sc_rs_r0 *)o); }
static void sc_rrelease_r0_v(void *o) { sc_rrelease_r0((sc_rs_r0 *)o); }

static sc_rs_r1 *sc_rretain_r1(sc_rs_r1 *o) {
  if (o && o->rc != SIZE_MAX) o->rc++;
  return o;
}
static void sc_rrelease_r1(sc_rs_r1 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    if (o->sc_fld_id) scr_str_release(o->sc_fld_id);
    if (o->sc_fld_kind) scr_str_release(o->sc_fld_kind);
    if (o->sc_fld_label) scr_str_release(o->sc_fld_label);
    if (o->sc_fld_surface) scr_str_release(o->sc_fld_surface);
    if (o->sc_fld_target) scr_str_release(o->sc_fld_target);
    scr_obj_free_note();
    free(o);
  }
}
static sc_rs_r1 *sc_rnew_r1(void) {
  sc_rs_r1 *o = calloc(1, sizeof *o);
  if (!o) { scr_trap("scriptc: out of memory\n"); }
  o->rc = 1;
  scr_obj_alloc_note();
  return o;
}
static void *sc_rretain_r1_v(void *o) { return sc_rretain_r1((sc_rs_r1 *)o); }
static void sc_rrelease_r1_v(void *o) { sc_rrelease_r1((sc_rs_r1 *)o); }

static sc_rs_r6 *sc_rretain_r6(sc_rs_r6 *o) {
  if (o && o->rc != SIZE_MAX) o->rc++;
  return o;
}
static void sc_rrelease_r6(sc_rs_r6 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    if (o->sc_fld_context) sc_rrelease_r0(o->sc_fld_context);
    if (o->sc_fld_id) scr_str_release(o->sc_fld_id);
    if (o->sc_fld_label) scr_str_release(o->sc_fld_label);
    scr_obj_free_note();
    free(o);
  }
}
static sc_rs_r6 *sc_rnew_r6(void) {
  sc_rs_r6 *o = calloc(1, sizeof *o);
  if (!o) { scr_trap("scriptc: out of memory\n"); }
  o->rc = 1;
  scr_obj_alloc_note();
  return o;
}
static void *sc_rretain_r6_v(void *o) { return sc_rretain_r6((sc_rs_r6 *)o); }
static void sc_rrelease_r6_v(void *o) { sc_rrelease_r6((sc_rs_r6 *)o); }

static ScrArr *sc_g_m1_profiles; /* profiles */
static ScrArr *sc_g_m1_userCandidates; /* userCandidates */
static ScrArr *sc_g_m1_systemCandidates; /* systemCandidates */
static double sc_g_m1_nextNodeId; /* nextNodeId */
static double sc_g_m1_nextCaseId; /* nextCaseId */
static bool sc_g_m0__x25_loaded; /* %loaded */
static bool sc_g_m1__x25_loaded; /* %loaded */
static bool sc_g_e__x25_loaded; /* %loaded */

static void sc_f__x25_init_0(void);
static void sc_f__x25_init_1(void);
static void sc_f__x25_init_2(void);
static void sc_f__x25_main(void);

static void sc_f__x25_init_0(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:1 */
  bool sc_t0 = sc_g_m0__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_m0__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:1 */
}

static void sc_f__x25_init_1(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:1 */
  bool sc_t0 = sc_g_m1__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_m1__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:1 */
  ScrArr *sc_t2 = scr_arr_new_ref(&sc_rretain_r6_v, &sc_rrelease_r6_v, NULL, 6);
  sc_rs_r6 *sc_t3 = sc_rnew_r6();
  ScrStr *sc_t4 = scr_str_retain((ScrStr *)&sc_lit_0);
  sc_t3->sc_fld_id = sc_t4;
  ScrStr *sc_t5 = scr_str_retain((ScrStr *)&sc_lit_1);
  sc_t3->sc_fld_label = sc_t5;
  sc_rs_r0 *sc_t6 = sc_rnew_r0();
  ScrStr *sc_t7 = scr_str_retain((ScrStr *)&sc_lit_0);
  sc_t6->sc_fld_runPhase = sc_t7;
  ScrStr *sc_t8 = scr_str_retain((ScrStr *)&sc_lit_2);
  sc_t6->sc_fld_queue = sc_t8;
  ScrStr *sc_t9 = scr_str_retain((ScrStr *)&sc_lit_3);
  sc_t6->sc_fld_compactMemory = sc_t9;
  bool sc_t10 = true;
  sc_t6->sc_fld_canCompactAgain = sc_t10;
  ScrStr *sc_t11 = scr_str_retain((ScrStr *)&sc_lit_4);
  sc_t6->sc_fld_goal = sc_t11;
  ScrStr *sc_t12 = scr_str_retain((ScrStr *)&sc_lit_5);
  sc_t6->sc_fld_selectedTurn = sc_t12;
  bool sc_t13 = false;
  sc_t6->sc_fld_forked = sc_t13;
  sc_t3->sc_fld_context = sc_t6;
  scr_arr_push_ref(sc_t2, sc_t3);
  sc_rs_r6 *sc_t14 = sc_rnew_r6();
  ScrStr *sc_t15 = scr_str_retain((ScrStr *)&sc_lit_6);
  sc_t14->sc_fld_id = sc_t15;
  ScrStr *sc_t16 = scr_str_retain((ScrStr *)&sc_lit_7);
  sc_t14->sc_fld_label = sc_t16;
  sc_rs_r0 *sc_t17 = sc_rnew_r0();
  ScrStr *sc_t18 = scr_str_retain((ScrStr *)&sc_lit_6);
  sc_t17->sc_fld_runPhase = sc_t18;
  ScrStr *sc_t19 = scr_str_retain((ScrStr *)&sc_lit_2);
  sc_t17->sc_fld_queue = sc_t19;
  ScrStr *sc_t20 = scr_str_retain((ScrStr *)&sc_lit_3);
  sc_t17->sc_fld_compactMemory = sc_t20;
  bool sc_t21 = true;
  sc_t17->sc_fld_canCompactAgain = sc_t21;
  ScrStr *sc_t22 = scr_str_retain((ScrStr *)&sc_lit_4);
  sc_t17->sc_fld_goal = sc_t22;
  ScrStr *sc_t23 = scr_str_retain((ScrStr *)&sc_lit_5);
  sc_t17->sc_fld_selectedTurn = sc_t23;
  bool sc_t24 = false;
  sc_t17->sc_fld_forked = sc_t24;
  sc_t14->sc_fld_context = sc_t17;
  scr_arr_push_ref(sc_t2, sc_t14);
  sc_rs_r6 *sc_t25 = sc_rnew_r6();
  ScrStr *sc_t26 = scr_str_retain((ScrStr *)&sc_lit_8);
  sc_t25->sc_fld_id = sc_t26;
  ScrStr *sc_t27 = scr_str_retain((ScrStr *)&sc_lit_9);
  sc_t25->sc_fld_label = sc_t27;
  sc_rs_r0 *sc_t28 = sc_rnew_r0();
  ScrStr *sc_t29 = scr_str_retain((ScrStr *)&sc_lit_10);
  sc_t28->sc_fld_runPhase = sc_t29;
  ScrStr *sc_t30 = scr_str_retain((ScrStr *)&sc_lit_2);
  sc_t28->sc_fld_queue = sc_t30;
  ScrStr *sc_t31 = scr_str_retain((ScrStr *)&sc_lit_3);
  sc_t28->sc_fld_compactMemory = sc_t31;
  bool sc_t32 = true;
  sc_t28->sc_fld_canCompactAgain = sc_t32;
  ScrStr *sc_t33 = scr_str_retain((ScrStr *)&sc_lit_11);
  sc_t28->sc_fld_goal = sc_t33;
  ScrStr *sc_t34 = scr_str_retain((ScrStr *)&sc_lit_5);
  sc_t28->sc_fld_selectedTurn = sc_t34;
  bool sc_t35 = false;
  sc_t28->sc_fld_forked = sc_t35;
  sc_t25->sc_fld_context = sc_t28;
  scr_arr_push_ref(sc_t2, sc_t25);
  sc_rs_r6 *sc_t36 = sc_rnew_r6();
  ScrStr *sc_t37 = scr_str_retain((ScrStr *)&sc_lit_12);
  sc_t36->sc_fld_id = sc_t37;
  ScrStr *sc_t38 = scr_str_retain((ScrStr *)&sc_lit_13);
  sc_t36->sc_fld_label = sc_t38;
  sc_rs_r0 *sc_t39 = sc_rnew_r0();
  ScrStr *sc_t40 = scr_str_retain((ScrStr *)&sc_lit_12);
  sc_t39->sc_fld_runPhase = sc_t40;
  ScrStr *sc_t41 = scr_str_retain((ScrStr *)&sc_lit_2);
  sc_t39->sc_fld_queue = sc_t41;
  ScrStr *sc_t42 = scr_str_retain((ScrStr *)&sc_lit_3);
  sc_t39->sc_fld_compactMemory = sc_t42;
  bool sc_t43 = true;
  sc_t39->sc_fld_canCompactAgain = sc_t43;
  ScrStr *sc_t44 = scr_str_retain((ScrStr *)&sc_lit_4);
  sc_t39->sc_fld_goal = sc_t44;
  ScrStr *sc_t45 = scr_str_retain((ScrStr *)&sc_lit_5);
  sc_t39->sc_fld_selectedTurn = sc_t45;
  bool sc_t46 = false;
  sc_t39->sc_fld_forked = sc_t46;
  sc_t36->sc_fld_context = sc_t39;
  scr_arr_push_ref(sc_t2, sc_t36);
  sc_rs_r6 *sc_t47 = sc_rnew_r6();
  ScrStr *sc_t48 = scr_str_retain((ScrStr *)&sc_lit_14);
  sc_t47->sc_fld_id = sc_t48;
  ScrStr *sc_t49 = scr_str_retain((ScrStr *)&sc_lit_15);
  sc_t47->sc_fld_label = sc_t49;
  sc_rs_r0 *sc_t50 = sc_rnew_r0();
  ScrStr *sc_t51 = scr_str_retain((ScrStr *)&sc_lit_6);
  sc_t50->sc_fld_runPhase = sc_t51;
  ScrStr *sc_t52 = scr_str_retain((ScrStr *)&sc_lit_2);
  sc_t50->sc_fld_queue = sc_t52;
  ScrStr *sc_t53 = scr_str_retain((ScrStr *)&sc_lit_16);
  sc_t50->sc_fld_compactMemory = sc_t53;
  bool sc_t54 = false;
  sc_t50->sc_fld_canCompactAgain = sc_t54;
  ScrStr *sc_t55 = scr_str_retain((ScrStr *)&sc_lit_4);
  sc_t50->sc_fld_goal = sc_t55;
  ScrStr *sc_t56 = scr_str_retain((ScrStr *)&sc_lit_5);
  sc_t50->sc_fld_selectedTurn = sc_t56;
  bool sc_t57 = false;
  sc_t50->sc_fld_forked = sc_t57;
  sc_t47->sc_fld_context = sc_t50;
  scr_arr_push_ref(sc_t2, sc_t47);
  sc_rs_r6 *sc_t58 = sc_rnew_r6();
  ScrStr *sc_t59 = scr_str_retain((ScrStr *)&sc_lit_17);
  sc_t58->sc_fld_id = sc_t59;
  ScrStr *sc_t60 = scr_str_retain((ScrStr *)&sc_lit_18);
  sc_t58->sc_fld_label = sc_t60;
  sc_rs_r0 *sc_t61 = sc_rnew_r0();
  ScrStr *sc_t62 = scr_str_retain((ScrStr *)&sc_lit_6);
  sc_t61->sc_fld_runPhase = sc_t62;
  ScrStr *sc_t63 = scr_str_retain((ScrStr *)&sc_lit_2);
  sc_t61->sc_fld_queue = sc_t63;
  ScrStr *sc_t64 = scr_str_retain((ScrStr *)&sc_lit_16);
  sc_t61->sc_fld_compactMemory = sc_t64;
  bool sc_t65 = true;
  sc_t61->sc_fld_canCompactAgain = sc_t65;
  ScrStr *sc_t66 = scr_str_retain((ScrStr *)&sc_lit_4);
  sc_t61->sc_fld_goal = sc_t66;
  ScrStr *sc_t67 = scr_str_retain((ScrStr *)&sc_lit_5);
  sc_t61->sc_fld_selectedTurn = sc_t67;
  bool sc_t68 = false;
  sc_t61->sc_fld_forked = sc_t68;
  sc_t58->sc_fld_context = sc_t61;
  scr_arr_push_ref(sc_t2, sc_t58);
  scr_arr_release(sc_g_m1_profiles);
  sc_g_m1_profiles = sc_t2; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:3 */
  ScrArr *sc_t69 = scr_arr_new_ref(&sc_rretain_r1_v, &sc_rrelease_r1_v, NULL, 8);
  sc_rs_r1 *sc_t70 = sc_rnew_r1();
  ScrStr *sc_t71 = scr_str_retain((ScrStr *)&sc_lit_19);
  sc_t70->sc_fld_id = sc_t71;
  ScrStr *sc_t72 = scr_str_retain((ScrStr *)&sc_lit_20);
  sc_t70->sc_fld_kind = sc_t72;
  ScrStr *sc_t73 = scr_str_retain((ScrStr *)&sc_lit_21);
  sc_t70->sc_fld_label = sc_t73;
  ScrStr *sc_t74 = scr_str_retain((ScrStr *)&sc_lit_22);
  sc_t70->sc_fld_target = sc_t74;
  ScrStr *sc_t75 = scr_str_retain((ScrStr *)&sc_lit_23);
  sc_t70->sc_fld_surface = sc_t75;
  scr_arr_push_ref(sc_t69, sc_t70);
  sc_rs_r1 *sc_t76 = sc_rnew_r1();
  ScrStr *sc_t77 = scr_str_retain((ScrStr *)&sc_lit_24);
  sc_t76->sc_fld_id = sc_t77;
  ScrStr *sc_t78 = scr_str_retain((ScrStr *)&sc_lit_20);
  sc_t76->sc_fld_kind = sc_t78;
  ScrStr *sc_t79 = scr_str_retain((ScrStr *)&sc_lit_25);
  sc_t76->sc_fld_label = sc_t79;
  ScrStr *sc_t80 = scr_str_retain((ScrStr *)&sc_lit_22);
  sc_t76->sc_fld_target = sc_t80;
  ScrStr *sc_t81 = scr_str_retain((ScrStr *)&sc_lit_23);
  sc_t76->sc_fld_surface = sc_t81;
  scr_arr_push_ref(sc_t69, sc_t76);
  sc_rs_r1 *sc_t82 = sc_rnew_r1();
  ScrStr *sc_t83 = scr_str_retain((ScrStr *)&sc_lit_26);
  sc_t82->sc_fld_id = sc_t83;
  ScrStr *sc_t84 = scr_str_retain((ScrStr *)&sc_lit_20);
  sc_t82->sc_fld_kind = sc_t84;
  ScrStr *sc_t85 = scr_str_retain((ScrStr *)&sc_lit_27);
  sc_t82->sc_fld_label = sc_t85;
  ScrStr *sc_t86 = scr_str_retain((ScrStr *)&sc_lit_22);
  sc_t82->sc_fld_target = sc_t86;
  ScrStr *sc_t87 = scr_str_retain((ScrStr *)&sc_lit_28);
  sc_t82->sc_fld_surface = sc_t87;
  scr_arr_push_ref(sc_t69, sc_t82);
  sc_rs_r1 *sc_t88 = sc_rnew_r1();
  ScrStr *sc_t89 = scr_str_retain((ScrStr *)&sc_lit_29);
  sc_t88->sc_fld_id = sc_t89;
  ScrStr *sc_t90 = scr_str_retain((ScrStr *)&sc_lit_20);
  sc_t88->sc_fld_kind = sc_t90;
  ScrStr *sc_t91 = scr_str_retain((ScrStr *)&sc_lit_30);
  sc_t88->sc_fld_label = sc_t91;
  ScrStr *sc_t92 = scr_str_retain((ScrStr *)&sc_lit_22);
  sc_t88->sc_fld_target = sc_t92;
  ScrStr *sc_t93 = scr_str_retain((ScrStr *)&sc_lit_31);
  sc_t88->sc_fld_surface = sc_t93;
  scr_arr_push_ref(sc_t69, sc_t88);
  sc_rs_r1 *sc_t94 = sc_rnew_r1();
  ScrStr *sc_t95 = scr_str_retain((ScrStr *)&sc_lit_32);
  sc_t94->sc_fld_id = sc_t95;
  ScrStr *sc_t96 = scr_str_retain((ScrStr *)&sc_lit_20);
  sc_t94->sc_fld_kind = sc_t96;
  ScrStr *sc_t97 = scr_str_retain((ScrStr *)&sc_lit_33);
  sc_t94->sc_fld_label = sc_t97;
  ScrStr *sc_t98 = scr_str_retain((ScrStr *)&sc_lit_5);
  sc_t94->sc_fld_target = sc_t98;
  ScrStr *sc_t99 = scr_str_retain((ScrStr *)&sc_lit_34);
  sc_t94->sc_fld_surface = sc_t99;
  scr_arr_push_ref(sc_t69, sc_t94);
  sc_rs_r1 *sc_t100 = sc_rnew_r1();
  ScrStr *sc_t101 = scr_str_retain((ScrStr *)&sc_lit_35);
  sc_t100->sc_fld_id = sc_t101;
  ScrStr *sc_t102 = scr_str_retain((ScrStr *)&sc_lit_20);
  sc_t100->sc_fld_kind = sc_t102;
  ScrStr *sc_t103 = scr_str_retain((ScrStr *)&sc_lit_36);
  sc_t100->sc_fld_label = sc_t103;
  ScrStr *sc_t104 = scr_str_retain((ScrStr *)&sc_lit_37);
  sc_t100->sc_fld_target = sc_t104;
  ScrStr *sc_t105 = scr_str_retain((ScrStr *)&sc_lit_34);
  sc_t100->sc_fld_surface = sc_t105;
  scr_arr_push_ref(sc_t69, sc_t100);
  sc_rs_r1 *sc_t106 = sc_rnew_r1();
  ScrStr *sc_t107 = scr_str_retain((ScrStr *)&sc_lit_38);
  sc_t106->sc_fld_id = sc_t107;
  ScrStr *sc_t108 = scr_str_retain((ScrStr *)&sc_lit_20);
  sc_t106->sc_fld_kind = sc_t108;
  ScrStr *sc_t109 = scr_str_retain((ScrStr *)&sc_lit_39);
  sc_t106->sc_fld_label = sc_t109;
  ScrStr *sc_t110 = scr_str_retain((ScrStr *)&sc_lit_5);
  sc_t106->sc_fld_target = sc_t110;
  ScrStr *sc_t111 = scr_str_retain((ScrStr *)&sc_lit_40);
  sc_t106->sc_fld_surface = sc_t111;
  scr_arr_push_ref(sc_t69, sc_t106);
  sc_rs_r1 *sc_t112 = sc_rnew_r1();
  ScrStr *sc_t113 = scr_str_retain((ScrStr *)&sc_lit_41);
  sc_t112->sc_fld_id = sc_t113;
  ScrStr *sc_t114 = scr_str_retain((ScrStr *)&sc_lit_20);
  sc_t112->sc_fld_kind = sc_t114;
  ScrStr *sc_t115 = scr_str_retain((ScrStr *)&sc_lit_42);
  sc_t112->sc_fld_label = sc_t115;
  ScrStr *sc_t116 = scr_str_retain((ScrStr *)&sc_lit_37);
  sc_t112->sc_fld_target = sc_t116;
  ScrStr *sc_t117 = scr_str_retain((ScrStr *)&sc_lit_40);
  sc_t112->sc_fld_surface = sc_t117;
  scr_arr_push_ref(sc_t69, sc_t112);
  scr_arr_release(sc_g_m1_userCandidates);
  sc_g_m1_userCandidates = sc_t69; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:3 */
  ScrArr *sc_t118 = scr_arr_new_ref(&sc_rretain_r1_v, &sc_rrelease_r1_v, NULL, 6);
  sc_rs_r1 *sc_t119 = sc_rnew_r1();
  ScrStr *sc_t120 = scr_str_retain((ScrStr *)&sc_lit_43);
  sc_t119->sc_fld_id = sc_t120;
  ScrStr *sc_t121 = scr_str_retain((ScrStr *)&sc_lit_44);
  sc_t119->sc_fld_kind = sc_t121;
  ScrStr *sc_t122 = scr_str_retain((ScrStr *)&sc_lit_45);
  sc_t119->sc_fld_label = sc_t122;
  ScrStr *sc_t123 = scr_str_retain((ScrStr *)&sc_lit_22);
  sc_t119->sc_fld_target = sc_t123;
  ScrStr *sc_t124 = scr_str_retain((ScrStr *)&sc_lit_46);
  sc_t119->sc_fld_surface = sc_t124;
  scr_arr_push_ref(sc_t118, sc_t119);
  sc_rs_r1 *sc_t125 = sc_rnew_r1();
  ScrStr *sc_t126 = scr_str_retain((ScrStr *)&sc_lit_47);
  sc_t125->sc_fld_id = sc_t126;
  ScrStr *sc_t127 = scr_str_retain((ScrStr *)&sc_lit_44);
  sc_t125->sc_fld_kind = sc_t127;
  ScrStr *sc_t128 = scr_str_retain((ScrStr *)&sc_lit_48);
  sc_t125->sc_fld_label = sc_t128;
  ScrStr *sc_t129 = scr_str_retain((ScrStr *)&sc_lit_22);
  sc_t125->sc_fld_target = sc_t129;
  ScrStr *sc_t130 = scr_str_retain((ScrStr *)&sc_lit_46);
  sc_t125->sc_fld_surface = sc_t130;
  scr_arr_push_ref(sc_t118, sc_t125);
  sc_rs_r1 *sc_t131 = sc_rnew_r1();
  ScrStr *sc_t132 = scr_str_retain((ScrStr *)&sc_lit_49);
  sc_t131->sc_fld_id = sc_t132;
  ScrStr *sc_t133 = scr_str_retain((ScrStr *)&sc_lit_44);
  sc_t131->sc_fld_kind = sc_t133;
  ScrStr *sc_t134 = scr_str_retain((ScrStr *)&sc_lit_50);
  sc_t131->sc_fld_label = sc_t134;
  ScrStr *sc_t135 = scr_str_retain((ScrStr *)&sc_lit_22);
  sc_t131->sc_fld_target = sc_t135;
  ScrStr *sc_t136 = scr_str_retain((ScrStr *)&sc_lit_46);
  sc_t131->sc_fld_surface = sc_t136;
  scr_arr_push_ref(sc_t118, sc_t131);
  sc_rs_r1 *sc_t137 = sc_rnew_r1();
  ScrStr *sc_t138 = scr_str_retain((ScrStr *)&sc_lit_51);
  sc_t137->sc_fld_id = sc_t138;
  ScrStr *sc_t139 = scr_str_retain((ScrStr *)&sc_lit_44);
  sc_t137->sc_fld_kind = sc_t139;
  ScrStr *sc_t140 = scr_str_retain((ScrStr *)&sc_lit_52);
  sc_t137->sc_fld_label = sc_t140;
  ScrStr *sc_t141 = scr_str_retain((ScrStr *)&sc_lit_22);
  sc_t137->sc_fld_target = sc_t141;
  ScrStr *sc_t142 = scr_str_retain((ScrStr *)&sc_lit_53);
  sc_t137->sc_fld_surface = sc_t142;
  scr_arr_push_ref(sc_t118, sc_t137);
  sc_rs_r1 *sc_t143 = sc_rnew_r1();
  ScrStr *sc_t144 = scr_str_retain((ScrStr *)&sc_lit_54);
  sc_t143->sc_fld_id = sc_t144;
  ScrStr *sc_t145 = scr_str_retain((ScrStr *)&sc_lit_44);
  sc_t143->sc_fld_kind = sc_t145;
  ScrStr *sc_t146 = scr_str_retain((ScrStr *)&sc_lit_55);
  sc_t143->sc_fld_label = sc_t146;
  ScrStr *sc_t147 = scr_str_retain((ScrStr *)&sc_lit_22);
  sc_t143->sc_fld_target = sc_t147;
  ScrStr *sc_t148 = scr_str_retain((ScrStr *)&sc_lit_53);
  sc_t143->sc_fld_surface = sc_t148;
  scr_arr_push_ref(sc_t118, sc_t143);
  sc_rs_r1 *sc_t149 = sc_rnew_r1();
  ScrStr *sc_t150 = scr_str_retain((ScrStr *)&sc_lit_56);
  sc_t149->sc_fld_id = sc_t150;
  ScrStr *sc_t151 = scr_str_retain((ScrStr *)&sc_lit_44);
  sc_t149->sc_fld_kind = sc_t151;
  ScrStr *sc_t152 = scr_str_retain((ScrStr *)&sc_lit_57);
  sc_t149->sc_fld_label = sc_t152;
  ScrStr *sc_t153 = scr_str_retain((ScrStr *)&sc_lit_22);
  sc_t149->sc_fld_target = sc_t153;
  ScrStr *sc_t154 = scr_str_retain((ScrStr *)&sc_lit_53);
  sc_t149->sc_fld_surface = sc_t154;
  scr_arr_push_ref(sc_t118, sc_t149);
  scr_arr_release(sc_g_m1_systemCandidates);
  sc_g_m1_systemCandidates = sc_t118; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:3 */
  double sc_t155 = 0.0;
  sc_g_m1_nextNodeId = sc_t155; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:3 */
  double sc_t156 = 0.0;
  sc_g_m1_nextCaseId = sc_t156; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:3 */
}

static void sc_f__x25_init_2(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:1 */
  bool sc_t0 = sc_g_e__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_e__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:1 */
  sc_f__x25_init_0(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:1 */
  sc_f__x25_init_1(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:2 */
}

static void sc_f__x25_main(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:1 */
  sc_f__x25_init_2(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/formal-proof.ts:1 */
}

static void sc_release_globals(void) {
  scr_arr_release(sc_g_m1_profiles);
  scr_arr_release(sc_g_m1_userCandidates);
  scr_arr_release(sc_g_m1_systemCandidates);
}

int main(int argc, char **argv) {
  scr_init();
  scr_error_vts[0].pre = 0; scr_error_vts[0].post = 4; /* Error */
  scr_error_vts[1].pre = 1; scr_error_vts[1].post = 1; /* TypeError */
  scr_error_vts[2].pre = 2; scr_error_vts[2].post = 2; /* RangeError */
  scr_error_vts[3].pre = 3; scr_error_vts[3].post = 3; /* SyntaxError */
  scr_error_vts[4].pre = 4; scr_error_vts[4].post = 4; /* DOMException */
  scr_lib_init(argc, argv);
  sc_f__x25_main();
  sc_release_globals();
  return scr_exit_code_hint_get();
}
