/* Generated by scriptc from /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts. Do not edit. */
#include "scr_runtime.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

static struct { size_t rc; size_t len; size_t cap; char data[3]; } sc_lit_0 =
    { SIZE_MAX, 2, 2, "&&" };
static struct { size_t rc; size_t len; size_t cap; char data[3]; } sc_lit_1 =
    { SIZE_MAX, 2, 2, "||" };
static struct { size_t rc; size_t len; size_t cap; char data[3]; } sc_lit_2 =
    { SIZE_MAX, 2, 2, "==" };
static struct { size_t rc; size_t len; size_t cap; char data[3]; } sc_lit_3 =
    { SIZE_MAX, 2, 2, "!=" };
static struct { size_t rc; size_t len; size_t cap; char data[3]; } sc_lit_4 =
    { SIZE_MAX, 2, 2, "<=" };
static struct { size_t rc; size_t len; size_t cap; char data[3]; } sc_lit_5 =
    { SIZE_MAX, 2, 2, ">=" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_6 =
    { SIZE_MAX, 1, 1, "+" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_7 =
    { SIZE_MAX, 1, 1, "-" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_8 =
    { SIZE_MAX, 1, 1, "*" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_9 =
    { SIZE_MAX, 1, 1, "/" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_10 =
    { SIZE_MAX, 1, 1, "%" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_11 =
    { SIZE_MAX, 1, 1, "!" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_12 =
    { SIZE_MAX, 1, 1, "<" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_13 =
    { SIZE_MAX, 1, 1, ">" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_14 =
    { SIZE_MAX, 1, 1, "{" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_15 =
    { SIZE_MAX, 1, 1, "}" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_16 =
    { SIZE_MAX, 1, 1, "[" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_17 =
    { SIZE_MAX, 1, 1, "]" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_18 =
    { SIZE_MAX, 1, 1, "(" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_19 =
    { SIZE_MAX, 1, 1, ")" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_20 =
    { SIZE_MAX, 1, 1, "," };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_21 =
    { SIZE_MAX, 1, 1, ":" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_22 =
    { SIZE_MAX, 1, 1, "\?" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_23 =
    { SIZE_MAX, 1, 1, "." };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_24 =
    { SIZE_MAX, 1, 1, "'" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_25 =
    { SIZE_MAX, 1, 1, "\"" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_26 =
    { SIZE_MAX, 1, 1, "\\" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_27 =
    { SIZE_MAX, 1, 1, "\010" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_28 =
    { SIZE_MAX, 1, 1, "b" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_29 =
    { SIZE_MAX, 1, 1, "\014" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_30 =
    { SIZE_MAX, 1, 1, "f" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_31 =
    { SIZE_MAX, 1, 1, "\012" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_32 =
    { SIZE_MAX, 1, 1, "n" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_33 =
    { SIZE_MAX, 1, 1, "\015" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_34 =
    { SIZE_MAX, 1, 1, "r" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_35 =
    { SIZE_MAX, 1, 1, "\011" };
static struct { size_t rc; size_t len; size_t cap; char data[2]; } sc_lit_36 =
    { SIZE_MAX, 1, 1, "t" };

typedef struct sc_o__x25_m1_RestrictedCelError sc_o__x25_m1_RestrictedCelError; /* class %m1.RestrictedCelError */
typedef struct sc_o__x25_m1_ModelOptionMapError sc_o__x25_m1_ModelOptionMapError; /* class %m1.ModelOptionMapError */
typedef struct sc_rs_r1 sc_rs_r1; /* record r1 { offset; type; value } */
typedef struct sc_rs_r2 sc_rs_r2; /* record r2 { offset; type } */
typedef struct sc_rs_r3 sc_rs_r3; /* record r3 { elements; offset; type } */
typedef struct sc_rs_r4 sc_rs_r4; /* record r4 { key; offset; value } */
typedef struct sc_rs_r5 sc_rs_r5; /* record r5 { entries; offset; type } */
typedef struct sc_rs_r6 sc_rs_r6; /* record r6 { offset; operand; operator; type } */
typedef struct sc_rs_r7 sc_rs_r7; /* record r7 { left; offset; operator; right; type } */
typedef struct sc_rs_r8 sc_rs_r8; /* record r8 { condition; offset; type; whenFalse; whenTrue } */
typedef struct sc_rs_r9 sc_rs_r9; /* record r9 { ; [key: string] } */
typedef struct sc_rs_r10 sc_rs_r10; /* record r10 { evaluate; source } */
typedef struct sc_rs_r11 sc_rs_r11; /* record r11 { evaluate; source } */
typedef struct sc_rs_r17 sc_rs_r17; /* record r17 { ; [key: string] } */

struct sc_o__x25_m1_RestrictedCelError { /* class %m1.RestrictedCelError */
  size_t rc;
  const ScrVt *vt;
  ScrStr *sc_fld_name; /* name */
  ScrStr *sc_fld_message; /* message */
  ScrStr *sc_fld__x25_code; /* %code */
  double sc_fld_offset; /* offset */
};
struct sc_o__x25_m1_ModelOptionMapError { /* class %m1.ModelOptionMapError */
  size_t rc;
  const ScrVt *vt;
  ScrStr *sc_fld_name; /* name */
  ScrStr *sc_fld_message; /* message */
  ScrStr *sc_fld__x25_code; /* %code */
};
struct sc_rs_r1 { /* record r1 { offset; type; value } */
  size_t rc;
  double sc_fld_offset; /* offset */
  ScrStr *sc_fld_type; /* type */
  ScrUnion *sc_fld_value; /* value */
};
struct sc_rs_r2 { /* record r2 { offset; type } */
  size_t rc;
  double sc_fld_offset; /* offset */
  ScrStr *sc_fld_type; /* type */
};
struct sc_rs_r3 { /* record r3 { elements; offset; type } */
  size_t rc;
  ScrArr *sc_fld_elements; /* elements */
  double sc_fld_offset; /* offset */
  ScrStr *sc_fld_type; /* type */
};
struct sc_rs_r4 { /* record r4 { key; offset; value } */
  size_t rc;
  ScrStr *sc_fld_key; /* key */
  double sc_fld_offset; /* offset */
  ScrUnion *sc_fld_value; /* value */
};
struct sc_rs_r5 { /* record r5 { entries; offset; type } */
  size_t rc;
  ScrArr *sc_fld_entries; /* entries */
  double sc_fld_offset; /* offset */
  ScrStr *sc_fld_type; /* type */
};
struct sc_rs_r6 { /* record r6 { offset; operand; operator; type } */
  size_t rc;
  double sc_fld_offset; /* offset */
  ScrUnion *sc_fld_operand; /* operand */
  ScrStr *sc_fld_operator; /* operator */
  ScrStr *sc_fld_type; /* type */
};
struct sc_rs_r7 { /* record r7 { left; offset; operator; right; type } */
  size_t rc;
  ScrUnion *sc_fld_left; /* left */
  double sc_fld_offset; /* offset */
  ScrStr *sc_fld_operator; /* operator */
  ScrUnion *sc_fld_right; /* right */
  ScrStr *sc_fld_type; /* type */
};
struct sc_rs_r8 { /* record r8 { condition; offset; type; whenFalse; whenTrue } */
  size_t rc;
  ScrUnion *sc_fld_condition; /* condition */
  double sc_fld_offset; /* offset */
  ScrStr *sc_fld_type; /* type */
  ScrUnion *sc_fld_whenFalse; /* whenFalse */
  ScrUnion *sc_fld_whenTrue; /* whenTrue */
};
struct sc_rs_r9 { /* record r9 { ; [key: string] } */
  size_t rc;
  ScrMap *sc_ovf; /* [key: string] overflow (string-keyed) */
};
struct sc_rs_r10 { /* record r10 { evaluate; source } */
  size_t rc;
  ScrClosure *sc_fld_evaluate; /* evaluate */
  ScrStr *sc_fld_source; /* source */
};
struct sc_rs_r11 { /* record r11 { evaluate; source } */
  size_t rc;
  ScrClosure *sc_fld_evaluate; /* evaluate */
  ScrStr *sc_fld_source; /* source */
};
struct sc_rs_r17 { /* record r17 { ; [key: string] } */
  size_t rc;
  ScrMap *sc_ovf; /* [key: string] overflow (string-keyed) */
};

typedef struct sc_vtt__x25_Error { /* vtable: hierarchy rooted at %Error */
  ScrVt head;
} sc_vtt__x25_Error;

static sc_o__x25_m1_RestrictedCelError *sc_retain__x25_m1_RestrictedCelError(sc_o__x25_m1_RestrictedCelError *o);
static void sc_release__x25_m1_RestrictedCelError(sc_o__x25_m1_RestrictedCelError *o);
static sc_o__x25_m1_RestrictedCelError *sc_new__x25_m1_RestrictedCelError(void);
static void sc_reld__x25_m1_RestrictedCelError(void *o0);
static sc_o__x25_m1_ModelOptionMapError *sc_retain__x25_m1_ModelOptionMapError(sc_o__x25_m1_ModelOptionMapError *o);
static void sc_release__x25_m1_ModelOptionMapError(sc_o__x25_m1_ModelOptionMapError *o);
static sc_o__x25_m1_ModelOptionMapError *sc_new__x25_m1_ModelOptionMapError(void);
static void sc_reld__x25_m1_ModelOptionMapError(void *o0);
static sc_rs_r1 *sc_rretain_r1(sc_rs_r1 *o);
static void sc_rrelease_r1(sc_rs_r1 *o);
static sc_rs_r1 *sc_rnew_r1(void);
static sc_rs_r2 *sc_rretain_r2(sc_rs_r2 *o);
static void sc_rrelease_r2(sc_rs_r2 *o);
static sc_rs_r2 *sc_rnew_r2(void);
static sc_rs_r3 *sc_rretain_r3(sc_rs_r3 *o);
static void sc_rrelease_r3(sc_rs_r3 *o);
static sc_rs_r3 *sc_rnew_r3(void);
static void sc_rtrace_r3(void *o, ScrTraceVisit visit, void *ctx);
static void sc_rgcfree_r3(void *o);
static sc_rs_r4 *sc_rretain_r4(sc_rs_r4 *o);
static void sc_rrelease_r4(sc_rs_r4 *o);
static sc_rs_r4 *sc_rnew_r4(void);
static void sc_rtrace_r4(void *o, ScrTraceVisit visit, void *ctx);
static void sc_rgcfree_r4(void *o);
static sc_rs_r5 *sc_rretain_r5(sc_rs_r5 *o);
static void sc_rrelease_r5(sc_rs_r5 *o);
static sc_rs_r5 *sc_rnew_r5(void);
static void sc_rtrace_r5(void *o, ScrTraceVisit visit, void *ctx);
static void sc_rgcfree_r5(void *o);
static sc_rs_r6 *sc_rretain_r6(sc_rs_r6 *o);
static void sc_rrelease_r6(sc_rs_r6 *o);
static sc_rs_r6 *sc_rnew_r6(void);
static void sc_rtrace_r6(void *o, ScrTraceVisit visit, void *ctx);
static void sc_rgcfree_r6(void *o);
static sc_rs_r7 *sc_rretain_r7(sc_rs_r7 *o);
static void sc_rrelease_r7(sc_rs_r7 *o);
static sc_rs_r7 *sc_rnew_r7(void);
static void sc_rtrace_r7(void *o, ScrTraceVisit visit, void *ctx);
static void sc_rgcfree_r7(void *o);
static sc_rs_r8 *sc_rretain_r8(sc_rs_r8 *o);
static void sc_rrelease_r8(sc_rs_r8 *o);
static sc_rs_r8 *sc_rnew_r8(void);
static void sc_rtrace_r8(void *o, ScrTraceVisit visit, void *ctx);
static void sc_rgcfree_r8(void *o);
static sc_rs_r9 *sc_rretain_r9(sc_rs_r9 *o);
static void sc_rrelease_r9(sc_rs_r9 *o);
static sc_rs_r9 *sc_rnew_r9(void);
static void sc_rtrace_r9(void *o, ScrTraceVisit visit, void *ctx);
static void sc_rgcfree_r9(void *o);
static sc_rs_r10 *sc_rretain_r10(sc_rs_r10 *o);
static void sc_rrelease_r10(sc_rs_r10 *o);
static sc_rs_r10 *sc_rnew_r10(void);
static void sc_rtrace_r10(void *o, ScrTraceVisit visit, void *ctx);
static void sc_rgcfree_r10(void *o);
static sc_rs_r11 *sc_rretain_r11(sc_rs_r11 *o);
static void sc_rrelease_r11(sc_rs_r11 *o);
static sc_rs_r11 *sc_rnew_r11(void);
static void sc_rtrace_r11(void *o, ScrTraceVisit visit, void *ctx);
static void sc_rgcfree_r11(void *o);
static sc_rs_r17 *sc_rretain_r17(sc_rs_r17 *o);
static void sc_rrelease_r17(sc_rs_r17 *o);
static sc_rs_r17 *sc_rnew_r17(void);

static const sc_vtt__x25_Error sc_vtable__x25_m1_RestrictedCelError = { /* class %m1.RestrictedCelError */
  { 5, 5, &sc_reld__x25_m1_RestrictedCelError }
};
static const sc_vtt__x25_Error sc_vtable__x25_m1_ModelOptionMapError = { /* class %m1.ModelOptionMapError */
  { 6, 6, &sc_reld__x25_m1_ModelOptionMapError }
};

static sc_o__x25_m1_RestrictedCelError *sc_retain__x25_m1_RestrictedCelError(sc_o__x25_m1_RestrictedCelError *o) {
  if (o && o->rc != SIZE_MAX) o->rc++;
  return o;
}
static void sc_release__x25_m1_RestrictedCelError(sc_o__x25_m1_RestrictedCelError *o) {
  if (!o || o->rc == SIZE_MAX) return;
  o->vt->release(o); /* the DYNAMIC class's teardown */
}
static void sc_reld__x25_m1_RestrictedCelError(void *o0) {
  sc_o__x25_m1_RestrictedCelError *o = (sc_o__x25_m1_RestrictedCelError *)o0;
  if (--o->rc == 0) {
    if (o->sc_fld_name) scr_str_release(o->sc_fld_name);
    if (o->sc_fld_message) scr_str_release(o->sc_fld_message);
    if (o->sc_fld__x25_code) scr_str_release(o->sc_fld__x25_code);
    scr_obj_free_note();
    free(o);
  }
}
static sc_o__x25_m1_RestrictedCelError *sc_new__x25_m1_RestrictedCelError(void) {
  sc_o__x25_m1_RestrictedCelError *o = calloc(1, sizeof *o);
  if (!o) { scr_trap("scriptc: out of memory\n"); }
  o->rc = 1;
  o->vt = &sc_vtable__x25_m1_RestrictedCelError.head;
  scr_obj_alloc_note();
  return o;
}
static void *sc_retain__x25_m1_RestrictedCelError_v(void *o) { return sc_retain__x25_m1_RestrictedCelError((sc_o__x25_m1_RestrictedCelError *)o); }
static void sc_release__x25_m1_RestrictedCelError_v(void *o) { sc_release__x25_m1_RestrictedCelError((sc_o__x25_m1_RestrictedCelError *)o); }

static sc_o__x25_m1_ModelOptionMapError *sc_retain__x25_m1_ModelOptionMapError(sc_o__x25_m1_ModelOptionMapError *o) {
  if (o && o->rc != SIZE_MAX) o->rc++;
  return o;
}
static void sc_release__x25_m1_ModelOptionMapError(sc_o__x25_m1_ModelOptionMapError *o) {
  if (!o || o->rc == SIZE_MAX) return;
  o->vt->release(o); /* the DYNAMIC class's teardown */
}
static void sc_reld__x25_m1_ModelOptionMapError(void *o0) {
  sc_o__x25_m1_ModelOptionMapError *o = (sc_o__x25_m1_ModelOptionMapError *)o0;
  if (--o->rc == 0) {
    if (o->sc_fld_name) scr_str_release(o->sc_fld_name);
    if (o->sc_fld_message) scr_str_release(o->sc_fld_message);
    if (o->sc_fld__x25_code) scr_str_release(o->sc_fld__x25_code);
    scr_obj_free_note();
    free(o);
  }
}
static sc_o__x25_m1_ModelOptionMapError *sc_new__x25_m1_ModelOptionMapError(void) {
  sc_o__x25_m1_ModelOptionMapError *o = calloc(1, sizeof *o);
  if (!o) { scr_trap("scriptc: out of memory\n"); }
  o->rc = 1;
  o->vt = &sc_vtable__x25_m1_ModelOptionMapError.head;
  scr_obj_alloc_note();
  return o;
}
static void *sc_retain__x25_m1_ModelOptionMapError_v(void *o) { return sc_retain__x25_m1_ModelOptionMapError((sc_o__x25_m1_ModelOptionMapError *)o); }
static void sc_release__x25_m1_ModelOptionMapError_v(void *o) { sc_release__x25_m1_ModelOptionMapError((sc_o__x25_m1_ModelOptionMapError *)o); }

static sc_rs_r1 *sc_rretain_r1(sc_rs_r1 *o) {
  if (o && o->rc != SIZE_MAX) o->rc++;
  return o;
}
static void sc_rrelease_r1(sc_rs_r1 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    if (o->sc_fld_type) scr_str_release(o->sc_fld_type);
    if (o->sc_fld_value) scr_union_release(o->sc_fld_value);
    scr_obj_free_note();
    free(o);
  }
}
static sc_rs_r1 *sc_rnew_r1(void) {
  sc_rs_r1 *o = calloc(1, sizeof *o);
  if (!o) { scr_trap("scriptc: out of memory\n"); }
  o->rc = 1;
  scr_obj_alloc_note();
  return o;
}
static void *sc_rretain_r1_v(void *o) { return sc_rretain_r1((sc_rs_r1 *)o); }
static void sc_rrelease_r1_v(void *o) { sc_rrelease_r1((sc_rs_r1 *)o); }

static sc_rs_r2 *sc_rretain_r2(sc_rs_r2 *o) {
  if (o && o->rc != SIZE_MAX) o->rc++;
  return o;
}
static void sc_rrelease_r2(sc_rs_r2 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    if (o->sc_fld_type) scr_str_release(o->sc_fld_type);
    scr_obj_free_note();
    free(o);
  }
}
static sc_rs_r2 *sc_rnew_r2(void) {
  sc_rs_r2 *o = calloc(1, sizeof *o);
  if (!o) { scr_trap("scriptc: out of memory\n"); }
  o->rc = 1;
  scr_obj_alloc_note();
  return o;
}
static void *sc_rretain_r2_v(void *o) { return sc_rretain_r2((sc_rs_r2 *)o); }
static void sc_rrelease_r2_v(void *o) { sc_rrelease_r2((sc_rs_r2 *)o); }

static sc_rs_r3 *sc_rretain_r3(sc_rs_r3 *o) {
  if (o && o->rc != SIZE_MAX) {
    o->rc++;
    scr_cyc_mark_live(o);
  }
  return o;
}
static void sc_rrelease_r3(sc_rs_r3 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    scr_cyc_on_dead(o);
    if (o->sc_fld_elements) scr_arr_release(o->sc_fld_elements);
    if (o->sc_fld_type) scr_str_release(o->sc_fld_type);
    scr_obj_free_note();
    scr_cyc_free(o);
  } else {
    scr_cyc_on_release(o); /* possible cycle root; may collect */
  }
}
static sc_rs_r3 *sc_rnew_r3(void) {
  sc_rs_r3 *o = scr_cyc_alloc(sizeof *o, &sc_rtrace_r3, &sc_rgcfree_r3);
  o->rc = 1;
  scr_obj_alloc_note();
  return o;
}
static void sc_rtrace_r3(void *o0, ScrTraceVisit visit, void *ctx) {
  sc_rs_r3 *o = (sc_rs_r3 *)o0;
  visit(o->sc_fld_elements, ctx); /* elements */
}
static void sc_rgcfree_r3(void *o0) {
  sc_rs_r3 *o = (sc_rs_r3 *)o0;
  if (o->sc_fld_type) scr_str_release(o->sc_fld_type); /* type (acyclic) */
  scr_obj_free_note();
  scr_cyc_free(o0);
}
static void *sc_rretain_r3_v(void *o) { return sc_rretain_r3((sc_rs_r3 *)o); }
static void sc_rrelease_r3_v(void *o) { sc_rrelease_r3((sc_rs_r3 *)o); }

static sc_rs_r4 *sc_rretain_r4(sc_rs_r4 *o) {
  if (o && o->rc != SIZE_MAX) {
    o->rc++;
    scr_cyc_mark_live(o);
  }
  return o;
}
static void sc_rrelease_r4(sc_rs_r4 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    scr_cyc_on_dead(o);
    if (o->sc_fld_key) scr_str_release(o->sc_fld_key);
    if (o->sc_fld_value) scr_union_release(o->sc_fld_value);
    scr_obj_free_note();
    scr_cyc_free(o);
  } else {
    scr_cyc_on_release(o); /* possible cycle root; may collect */
  }
}
static sc_rs_r4 *sc_rnew_r4(void) {
  sc_rs_r4 *o = scr_cyc_alloc(sizeof *o, &sc_rtrace_r4, &sc_rgcfree_r4);
  o->rc = 1;
  scr_obj_alloc_note();
  return o;
}
static void sc_rtrace_r4(void *o0, ScrTraceVisit visit, void *ctx) {
  sc_rs_r4 *o = (sc_rs_r4 *)o0;
  visit(o->sc_fld_value, ctx); /* value */
}
static void sc_rgcfree_r4(void *o0) {
  sc_rs_r4 *o = (sc_rs_r4 *)o0;
  if (o->sc_fld_key) scr_str_release(o->sc_fld_key); /* key (acyclic) */
  scr_obj_free_note();
  scr_cyc_free(o0);
}
static void *sc_rretain_r4_v(void *o) { return sc_rretain_r4((sc_rs_r4 *)o); }
static void sc_rrelease_r4_v(void *o) { sc_rrelease_r4((sc_rs_r4 *)o); }

static sc_rs_r5 *sc_rretain_r5(sc_rs_r5 *o) {
  if (o && o->rc != SIZE_MAX) {
    o->rc++;
    scr_cyc_mark_live(o);
  }
  return o;
}
static void sc_rrelease_r5(sc_rs_r5 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    scr_cyc_on_dead(o);
    if (o->sc_fld_entries) scr_arr_release(o->sc_fld_entries);
    if (o->sc_fld_type) scr_str_release(o->sc_fld_type);
    scr_obj_free_note();
    scr_cyc_free(o);
  } else {
    scr_cyc_on_release(o); /* possible cycle root; may collect */
  }
}
static sc_rs_r5 *sc_rnew_r5(void) {
  sc_rs_r5 *o = scr_cyc_alloc(sizeof *o, &sc_rtrace_r5, &sc_rgcfree_r5);
  o->rc = 1;
  scr_obj_alloc_note();
  return o;
}
static void sc_rtrace_r5(void *o0, ScrTraceVisit visit, void *ctx) {
  sc_rs_r5 *o = (sc_rs_r5 *)o0;
  visit(o->sc_fld_entries, ctx); /* entries */
}
static void sc_rgcfree_r5(void *o0) {
  sc_rs_r5 *o = (sc_rs_r5 *)o0;
  if (o->sc_fld_type) scr_str_release(o->sc_fld_type); /* type (acyclic) */
  scr_obj_free_note();
  scr_cyc_free(o0);
}
static void *sc_rretain_r5_v(void *o) { return sc_rretain_r5((sc_rs_r5 *)o); }
static void sc_rrelease_r5_v(void *o) { sc_rrelease_r5((sc_rs_r5 *)o); }

static sc_rs_r6 *sc_rretain_r6(sc_rs_r6 *o) {
  if (o && o->rc != SIZE_MAX) {
    o->rc++;
    scr_cyc_mark_live(o);
  }
  return o;
}
static void sc_rrelease_r6(sc_rs_r6 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    scr_cyc_on_dead(o);
    if (o->sc_fld_operand) scr_union_release(o->sc_fld_operand);
    if (o->sc_fld_operator) scr_str_release(o->sc_fld_operator);
    if (o->sc_fld_type) scr_str_release(o->sc_fld_type);
    scr_obj_free_note();
    scr_cyc_free(o);
  } else {
    scr_cyc_on_release(o); /* possible cycle root; may collect */
  }
}
static sc_rs_r6 *sc_rnew_r6(void) {
  sc_rs_r6 *o = scr_cyc_alloc(sizeof *o, &sc_rtrace_r6, &sc_rgcfree_r6);
  o->rc = 1;
  scr_obj_alloc_note();
  return o;
}
static void sc_rtrace_r6(void *o0, ScrTraceVisit visit, void *ctx) {
  sc_rs_r6 *o = (sc_rs_r6 *)o0;
  visit(o->sc_fld_operand, ctx); /* operand */
}
static void sc_rgcfree_r6(void *o0) {
  sc_rs_r6 *o = (sc_rs_r6 *)o0;
  if (o->sc_fld_operator) scr_str_release(o->sc_fld_operator); /* operator (acyclic) */
  if (o->sc_fld_type) scr_str_release(o->sc_fld_type); /* type (acyclic) */
  scr_obj_free_note();
  scr_cyc_free(o0);
}
static void *sc_rretain_r6_v(void *o) { return sc_rretain_r6((sc_rs_r6 *)o); }
static void sc_rrelease_r6_v(void *o) { sc_rrelease_r6((sc_rs_r6 *)o); }

static sc_rs_r7 *sc_rretain_r7(sc_rs_r7 *o) {
  if (o && o->rc != SIZE_MAX) {
    o->rc++;
    scr_cyc_mark_live(o);
  }
  return o;
}
static void sc_rrelease_r7(sc_rs_r7 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    scr_cyc_on_dead(o);
    if (o->sc_fld_left) scr_union_release(o->sc_fld_left);
    if (o->sc_fld_operator) scr_str_release(o->sc_fld_operator);
    if (o->sc_fld_right) scr_union_release(o->sc_fld_right);
    if (o->sc_fld_type) scr_str_release(o->sc_fld_type);
    scr_obj_free_note();
    scr_cyc_free(o);
  } else {
    scr_cyc_on_release(o); /* possible cycle root; may collect */
  }
}
static sc_rs_r7 *sc_rnew_r7(void) {
  sc_rs_r7 *o = scr_cyc_alloc(sizeof *o, &sc_rtrace_r7, &sc_rgcfree_r7);
  o->rc = 1;
  scr_obj_alloc_note();
  return o;
}
static void sc_rtrace_r7(void *o0, ScrTraceVisit visit, void *ctx) {
  sc_rs_r7 *o = (sc_rs_r7 *)o0;
  visit(o->sc_fld_left, ctx); /* left */
  visit(o->sc_fld_right, ctx); /* right */
}
static void sc_rgcfree_r7(void *o0) {
  sc_rs_r7 *o = (sc_rs_r7 *)o0;
  if (o->sc_fld_operator) scr_str_release(o->sc_fld_operator); /* operator (acyclic) */
  if (o->sc_fld_type) scr_str_release(o->sc_fld_type); /* type (acyclic) */
  scr_obj_free_note();
  scr_cyc_free(o0);
}
static void *sc_rretain_r7_v(void *o) { return sc_rretain_r7((sc_rs_r7 *)o); }
static void sc_rrelease_r7_v(void *o) { sc_rrelease_r7((sc_rs_r7 *)o); }

static sc_rs_r8 *sc_rretain_r8(sc_rs_r8 *o) {
  if (o && o->rc != SIZE_MAX) {
    o->rc++;
    scr_cyc_mark_live(o);
  }
  return o;
}
static void sc_rrelease_r8(sc_rs_r8 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    scr_cyc_on_dead(o);
    if (o->sc_fld_condition) scr_union_release(o->sc_fld_condition);
    if (o->sc_fld_type) scr_str_release(o->sc_fld_type);
    if (o->sc_fld_whenFalse) scr_union_release(o->sc_fld_whenFalse);
    if (o->sc_fld_whenTrue) scr_union_release(o->sc_fld_whenTrue);
    scr_obj_free_note();
    scr_cyc_free(o);
  } else {
    scr_cyc_on_release(o); /* possible cycle root; may collect */
  }
}
static sc_rs_r8 *sc_rnew_r8(void) {
  sc_rs_r8 *o = scr_cyc_alloc(sizeof *o, &sc_rtrace_r8, &sc_rgcfree_r8);
  o->rc = 1;
  scr_obj_alloc_note();
  return o;
}
static void sc_rtrace_r8(void *o0, ScrTraceVisit visit, void *ctx) {
  sc_rs_r8 *o = (sc_rs_r8 *)o0;
  visit(o->sc_fld_condition, ctx); /* condition */
  visit(o->sc_fld_whenFalse, ctx); /* whenFalse */
  visit(o->sc_fld_whenTrue, ctx); /* whenTrue */
}
static void sc_rgcfree_r8(void *o0) {
  sc_rs_r8 *o = (sc_rs_r8 *)o0;
  if (o->sc_fld_type) scr_str_release(o->sc_fld_type); /* type (acyclic) */
  scr_obj_free_note();
  scr_cyc_free(o0);
}
static void *sc_rretain_r8_v(void *o) { return sc_rretain_r8((sc_rs_r8 *)o); }
static void sc_rrelease_r8_v(void *o) { sc_rrelease_r8((sc_rs_r8 *)o); }

static sc_rs_r9 *sc_rretain_r9(sc_rs_r9 *o) {
  if (o && o->rc != SIZE_MAX) {
    o->rc++;
    scr_cyc_mark_live(o);
  }
  return o;
}
static void sc_rrelease_r9(sc_rs_r9 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    scr_cyc_on_dead(o);
    if (o->sc_ovf) scr_map_release(o->sc_ovf);
    scr_obj_free_note();
    scr_cyc_free(o);
  } else {
    scr_cyc_on_release(o); /* possible cycle root; may collect */
  }
}
static sc_rs_r9 *sc_rnew_r9(void) {
  sc_rs_r9 *o = scr_cyc_alloc(sizeof *o, &sc_rtrace_r9, &sc_rgcfree_r9);
  o->rc = 1;
  o->sc_ovf = scr_map_new(SCR_MAP_KEY_STR, SCR_MAP_VAL_REF, &scr_union_retain_v, &scr_union_release_v, &scr_union_trace_v);
  scr_obj_alloc_note();
  return o;
}
static void sc_rtrace_r9(void *o0, ScrTraceVisit visit, void *ctx) {
  sc_rs_r9 *o = (sc_rs_r9 *)o0;
  visit(o->sc_ovf, ctx); /* [key: string] overflow */
}
static void sc_rgcfree_r9(void *o0) {
  scr_obj_free_note();
  scr_cyc_free(o0);
}
static void *sc_rretain_r9_v(void *o) { return sc_rretain_r9((sc_rs_r9 *)o); }
static void sc_rrelease_r9_v(void *o) { sc_rrelease_r9((sc_rs_r9 *)o); }

static sc_rs_r10 *sc_rretain_r10(sc_rs_r10 *o) {
  if (o && o->rc != SIZE_MAX) {
    o->rc++;
    scr_cyc_mark_live(o);
  }
  return o;
}
static void sc_rrelease_r10(sc_rs_r10 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    scr_cyc_on_dead(o);
    if (o->sc_fld_evaluate) scr_closure_release(o->sc_fld_evaluate);
    if (o->sc_fld_source) scr_str_release(o->sc_fld_source);
    scr_obj_free_note();
    scr_cyc_free(o);
  } else {
    scr_cyc_on_release(o); /* possible cycle root; may collect */
  }
}
static sc_rs_r10 *sc_rnew_r10(void) {
  sc_rs_r10 *o = scr_cyc_alloc(sizeof *o, &sc_rtrace_r10, &sc_rgcfree_r10);
  o->rc = 1;
  scr_obj_alloc_note();
  return o;
}
static void sc_rtrace_r10(void *o0, ScrTraceVisit visit, void *ctx) {
  sc_rs_r10 *o = (sc_rs_r10 *)o0;
  visit(o->sc_fld_evaluate, ctx); /* evaluate */
}
static void sc_rgcfree_r10(void *o0) {
  sc_rs_r10 *o = (sc_rs_r10 *)o0;
  if (o->sc_fld_source) scr_str_release(o->sc_fld_source); /* source (acyclic) */
  scr_obj_free_note();
  scr_cyc_free(o0);
}
static void *sc_rretain_r10_v(void *o) { return sc_rretain_r10((sc_rs_r10 *)o); }
static void sc_rrelease_r10_v(void *o) { sc_rrelease_r10((sc_rs_r10 *)o); }

static sc_rs_r11 *sc_rretain_r11(sc_rs_r11 *o) {
  if (o && o->rc != SIZE_MAX) {
    o->rc++;
    scr_cyc_mark_live(o);
  }
  return o;
}
static void sc_rrelease_r11(sc_rs_r11 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    scr_cyc_on_dead(o);
    if (o->sc_fld_evaluate) scr_closure_release(o->sc_fld_evaluate);
    if (o->sc_fld_source) scr_str_release(o->sc_fld_source);
    scr_obj_free_note();
    scr_cyc_free(o);
  } else {
    scr_cyc_on_release(o); /* possible cycle root; may collect */
  }
}
static sc_rs_r11 *sc_rnew_r11(void) {
  sc_rs_r11 *o = scr_cyc_alloc(sizeof *o, &sc_rtrace_r11, &sc_rgcfree_r11);
  o->rc = 1;
  scr_obj_alloc_note();
  return o;
}
static void sc_rtrace_r11(void *o0, ScrTraceVisit visit, void *ctx) {
  sc_rs_r11 *o = (sc_rs_r11 *)o0;
  visit(o->sc_fld_evaluate, ctx); /* evaluate */
}
static void sc_rgcfree_r11(void *o0) {
  sc_rs_r11 *o = (sc_rs_r11 *)o0;
  if (o->sc_fld_source) scr_str_release(o->sc_fld_source); /* source (acyclic) */
  scr_obj_free_note();
  scr_cyc_free(o0);
}
static void *sc_rretain_r11_v(void *o) { return sc_rretain_r11((sc_rs_r11 *)o); }
static void sc_rrelease_r11_v(void *o) { sc_rrelease_r11((sc_rs_r11 *)o); }

static sc_rs_r17 *sc_rretain_r17(sc_rs_r17 *o) {
  if (o && o->rc != SIZE_MAX) o->rc++;
  return o;
}
static void sc_rrelease_r17(sc_rs_r17 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    if (o->sc_ovf) scr_map_release(o->sc_ovf);
    scr_obj_free_note();
    free(o);
  }
}
static sc_rs_r17 *sc_rnew_r17(void) {
  sc_rs_r17 *o = calloc(1, sizeof *o);
  if (!o) { scr_trap("scriptc: out of memory\n"); }
  o->rc = 1;
  o->sc_ovf = scr_map_new(SCR_MAP_KEY_STR, SCR_MAP_VAL_REF, &scr_str_retain_v, &scr_str_release_v, NULL);
  scr_obj_alloc_note();
  return o;
}
static void *sc_rretain_r17_v(void *o) { return sc_rretain_r17((sc_rs_r17 *)o); }
static void sc_rrelease_r17_v(void *o) { sc_rrelease_r17((sc_rs_r17 *)o); }

static ScrMap *sc_g_m4_DOUBLE_OPERATORS; /* DOUBLE_OPERATORS */
static ScrMap *sc_g_m4_SINGLE_OPERATORS; /* SINGLE_OPERATORS */
static ScrMap *sc_g_m4_PUNCTUATION; /* PUNCTUATION */
static sc_rs_r17 *sc_g_m4_SIMPLE_ESCAPES; /* SIMPLE_ESCAPES */
static ScrMap *sc_g_m5_programCache; /* programCache */
static ScrMap *sc_g_m5_optionMapCache; /* optionMapCache */
static ScrMap *sc_g_m5_expressionCache; /* expressionCache */
static bool sc_g_m0__x25_loaded; /* %loaded */
static bool sc_g_m1__x25_loaded; /* %loaded */
static bool sc_g_m2__x25_loaded; /* %loaded */
static bool sc_g_m3__x25_loaded; /* %loaded */
static bool sc_g_m4__x25_loaded; /* %loaded */
static bool sc_g_m5__x25_loaded; /* %loaded */
static bool sc_g_m6__x25_loaded; /* %loaded */
static bool sc_g_m7__x25_loaded; /* %loaded */
static bool sc_g_m8__x25_loaded; /* %loaded */
static bool sc_g_e__x25_loaded; /* %loaded */

static void sc_f__x25_init_0(void);
static void sc_f__x25_init_1(void);
static void sc_f__x25_init_2(void);
static void sc_f__x25_init_3(void);
static void sc_f__x25_init_4(void);
static void sc_f__x25_init_5(void);
static void sc_f__x25_init_6(void);
static void sc_f__x25_init_7(void);
static void sc_f__x25_init_8(void);
static void sc_f__x25_init_9(void);
static void sc_f__x25_main(void);

static void sc_f__x25_init_0(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  bool sc_t0 = sc_g_m0__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_m0__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
}

static void sc_f__x25_init_1(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  bool sc_t0 = sc_g_m1__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_m1__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
}

static void sc_f__x25_init_2(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  bool sc_t0 = sc_g_m2__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_m2__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  sc_f__x25_init_1(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:2 */
}

static void sc_f__x25_init_3(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  bool sc_t0 = sc_g_m3__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_m3__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  sc_f__x25_init_1(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
}

static void sc_f__x25_init_4(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  bool sc_t0 = sc_g_m4__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_m4__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  sc_f__x25_init_1(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  ScrMap *sc_t2 = scr_map_new(SCR_MAP_KEY_STR, SCR_MAP_VAL_F64, NULL, NULL, NULL);
  ScrArr *sc_t3 = scr_arr_new(SCR_ELEM_STR, 6);
  ScrStr *sc_t4 = scr_str_retain((ScrStr *)&sc_lit_0);
  scr_arr_push_ref(sc_t3, sc_t4);
  ScrStr *sc_t5 = scr_str_retain((ScrStr *)&sc_lit_1);
  scr_arr_push_ref(sc_t3, sc_t5);
  ScrStr *sc_t6 = scr_str_retain((ScrStr *)&sc_lit_2);
  scr_arr_push_ref(sc_t3, sc_t6);
  ScrStr *sc_t7 = scr_str_retain((ScrStr *)&sc_lit_3);
  scr_arr_push_ref(sc_t3, sc_t7);
  ScrStr *sc_t8 = scr_str_retain((ScrStr *)&sc_lit_4);
  scr_arr_push_ref(sc_t3, sc_t8);
  ScrStr *sc_t9 = scr_str_retain((ScrStr *)&sc_lit_5);
  scr_arr_push_ref(sc_t3, sc_t9);
  scr_set_add_all(sc_t2, sc_t3); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
  scr_map_release(sc_g_m4_DOUBLE_OPERATORS);
  sc_g_m4_DOUBLE_OPERATORS = sc_t2; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
  scr_arr_release(sc_t3);
  ScrMap *sc_t10 = scr_map_new(SCR_MAP_KEY_STR, SCR_MAP_VAL_F64, NULL, NULL, NULL);
  ScrArr *sc_t11 = scr_arr_new(SCR_ELEM_STR, 8);
  ScrStr *sc_t12 = scr_str_retain((ScrStr *)&sc_lit_6);
  scr_arr_push_ref(sc_t11, sc_t12);
  ScrStr *sc_t13 = scr_str_retain((ScrStr *)&sc_lit_7);
  scr_arr_push_ref(sc_t11, sc_t13);
  ScrStr *sc_t14 = scr_str_retain((ScrStr *)&sc_lit_8);
  scr_arr_push_ref(sc_t11, sc_t14);
  ScrStr *sc_t15 = scr_str_retain((ScrStr *)&sc_lit_9);
  scr_arr_push_ref(sc_t11, sc_t15);
  ScrStr *sc_t16 = scr_str_retain((ScrStr *)&sc_lit_10);
  scr_arr_push_ref(sc_t11, sc_t16);
  ScrStr *sc_t17 = scr_str_retain((ScrStr *)&sc_lit_11);
  scr_arr_push_ref(sc_t11, sc_t17);
  ScrStr *sc_t18 = scr_str_retain((ScrStr *)&sc_lit_12);
  scr_arr_push_ref(sc_t11, sc_t18);
  ScrStr *sc_t19 = scr_str_retain((ScrStr *)&sc_lit_13);
  scr_arr_push_ref(sc_t11, sc_t19);
  scr_set_add_all(sc_t10, sc_t11); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
  scr_map_release(sc_g_m4_SINGLE_OPERATORS);
  sc_g_m4_SINGLE_OPERATORS = sc_t10; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
  scr_arr_release(sc_t11);
  ScrMap *sc_t20 = scr_map_new(SCR_MAP_KEY_STR, SCR_MAP_VAL_F64, NULL, NULL, NULL);
  ScrArr *sc_t21 = scr_arr_new(SCR_ELEM_STR, 10);
  ScrStr *sc_t22 = scr_str_retain((ScrStr *)&sc_lit_14);
  scr_arr_push_ref(sc_t21, sc_t22);
  ScrStr *sc_t23 = scr_str_retain((ScrStr *)&sc_lit_15);
  scr_arr_push_ref(sc_t21, sc_t23);
  ScrStr *sc_t24 = scr_str_retain((ScrStr *)&sc_lit_16);
  scr_arr_push_ref(sc_t21, sc_t24);
  ScrStr *sc_t25 = scr_str_retain((ScrStr *)&sc_lit_17);
  scr_arr_push_ref(sc_t21, sc_t25);
  ScrStr *sc_t26 = scr_str_retain((ScrStr *)&sc_lit_18);
  scr_arr_push_ref(sc_t21, sc_t26);
  ScrStr *sc_t27 = scr_str_retain((ScrStr *)&sc_lit_19);
  scr_arr_push_ref(sc_t21, sc_t27);
  ScrStr *sc_t28 = scr_str_retain((ScrStr *)&sc_lit_20);
  scr_arr_push_ref(sc_t21, sc_t28);
  ScrStr *sc_t29 = scr_str_retain((ScrStr *)&sc_lit_21);
  scr_arr_push_ref(sc_t21, sc_t29);
  ScrStr *sc_t30 = scr_str_retain((ScrStr *)&sc_lit_22);
  scr_arr_push_ref(sc_t21, sc_t30);
  ScrStr *sc_t31 = scr_str_retain((ScrStr *)&sc_lit_23);
  scr_arr_push_ref(sc_t21, sc_t31);
  scr_set_add_all(sc_t20, sc_t21); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
  scr_map_release(sc_g_m4_PUNCTUATION);
  sc_g_m4_PUNCTUATION = sc_t20; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
  scr_arr_release(sc_t21);
  sc_rs_r17 *sc_t32 = sc_rnew_r17();
  ScrStr *sc_t33 = scr_str_retain((ScrStr *)&sc_lit_24);
  scr_map_set_str_ref(sc_t32->sc_ovf, (ScrStr *)&sc_lit_24, sc_t33);
  ScrStr *sc_t34 = scr_str_retain((ScrStr *)&sc_lit_25);
  scr_map_set_str_ref(sc_t32->sc_ovf, (ScrStr *)&sc_lit_25, sc_t34);
  ScrStr *sc_t35 = scr_str_retain((ScrStr *)&sc_lit_26);
  scr_map_set_str_ref(sc_t32->sc_ovf, (ScrStr *)&sc_lit_26, sc_t35);
  ScrStr *sc_t36 = scr_str_retain((ScrStr *)&sc_lit_27);
  scr_map_set_str_ref(sc_t32->sc_ovf, (ScrStr *)&sc_lit_28, sc_t36);
  ScrStr *sc_t37 = scr_str_retain((ScrStr *)&sc_lit_29);
  scr_map_set_str_ref(sc_t32->sc_ovf, (ScrStr *)&sc_lit_30, sc_t37);
  ScrStr *sc_t38 = scr_str_retain((ScrStr *)&sc_lit_31);
  scr_map_set_str_ref(sc_t32->sc_ovf, (ScrStr *)&sc_lit_32, sc_t38);
  ScrStr *sc_t39 = scr_str_retain((ScrStr *)&sc_lit_33);
  scr_map_set_str_ref(sc_t32->sc_ovf, (ScrStr *)&sc_lit_34, sc_t39);
  ScrStr *sc_t40 = scr_str_retain((ScrStr *)&sc_lit_35);
  scr_map_set_str_ref(sc_t32->sc_ovf, (ScrStr *)&sc_lit_36, sc_t40);
  sc_rrelease_r17(sc_g_m4_SIMPLE_ESCAPES);
  sc_g_m4_SIMPLE_ESCAPES = sc_t32; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
}

static void sc_f__x25_init_5(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  bool sc_t0 = sc_g_m5__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_m5__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  sc_f__x25_init_2(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  sc_f__x25_init_3(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:2 */
  sc_f__x25_init_4(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
  sc_f__x25_init_1(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
  ScrMap *sc_t2 = scr_map_new(SCR_MAP_KEY_STR, SCR_MAP_VAL_REF, &sc_rretain_r10_v, &sc_rrelease_r10_v, &sc_rtrace_r10);
  scr_map_release(sc_g_m5_programCache);
  sc_g_m5_programCache = sc_t2; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
  ScrMap *sc_t3 = scr_map_new(SCR_MAP_KEY_STR, SCR_MAP_VAL_REF, &sc_rretain_r11_v, &sc_rrelease_r11_v, &sc_rtrace_r11);
  scr_map_release(sc_g_m5_optionMapCache);
  sc_g_m5_optionMapCache = sc_t3; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
  ScrMap *sc_t4 = scr_map_new(SCR_MAP_KEY_STR, SCR_MAP_VAL_REF, &scr_union_retain_v, &scr_union_release_v, &scr_union_trace_v);
  scr_map_release(sc_g_m5_expressionCache);
  sc_g_m5_expressionCache = sc_t4; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
}

static void sc_f__x25_init_6(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  bool sc_t0 = sc_g_m6__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_m6__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  sc_f__x25_init_1(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
}

static void sc_f__x25_init_7(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  bool sc_t0 = sc_g_m7__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_m7__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  sc_f__x25_init_5(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  sc_f__x25_init_6(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:2 */
  sc_f__x25_init_1(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
}

static void sc_f__x25_init_8(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  bool sc_t0 = sc_g_m8__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_m8__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  sc_f__x25_init_5(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  sc_f__x25_init_6(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  sc_f__x25_init_7(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:2 */
  sc_f__x25_init_4(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
  sc_f__x25_init_1(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:3 */
}

static void sc_f__x25_init_9(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  bool sc_t0 = sc_g_e__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_e__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  sc_f__x25_init_0(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  sc_f__x25_init_8(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:2 */
}

static void sc_f__x25_main(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
  sc_f__x25_init_9(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/model-option-map.ts:1 */
}

static void sc_release_globals(void) {
  scr_map_release(sc_g_m4_DOUBLE_OPERATORS);
  scr_map_release(sc_g_m4_SINGLE_OPERATORS);
  scr_map_release(sc_g_m4_PUNCTUATION);
  sc_rrelease_r17(sc_g_m4_SIMPLE_ESCAPES);
  scr_map_release(sc_g_m5_programCache);
  scr_map_release(sc_g_m5_optionMapCache);
  scr_map_release(sc_g_m5_expressionCache);
}

int main(int argc, char **argv) {
  scr_init();
  scr_error_vts[0].pre = 0; scr_error_vts[0].post = 6; /* Error */
  scr_error_vts[1].pre = 1; scr_error_vts[1].post = 1; /* TypeError */
  scr_error_vts[2].pre = 2; scr_error_vts[2].post = 2; /* RangeError */
  scr_error_vts[3].pre = 3; scr_error_vts[3].post = 3; /* SyntaxError */
  scr_error_vts[4].pre = 4; scr_error_vts[4].post = 4; /* DOMException */
  scr_lib_init(argc, argv);
  sc_f__x25_main();
  sc_release_globals();
  return scr_exit_code_hint_get();
}
