/* Generated by scriptc from /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/tui.ts. Do not edit. */
#include "scr_runtime.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

static bool sc_g_m0__x25_loaded; /* %loaded */
static bool sc_g_m1__x25_loaded; /* %loaded */
static bool sc_g_e__x25_loaded; /* %loaded */

static void sc_f__x25_init_0(void);
static void sc_f__x25_init_1(void);
static void sc_f__x25_init_2(void);
static void sc_f__x25_main(void);

static void sc_f__x25_init_0(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/tui.ts:1 */
  bool sc_t0 = sc_g_m0__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/tui.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_m0__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/tui.ts:1 */
}

static void sc_f__x25_init_1(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/tui.ts:1 */
  bool sc_t0 = sc_g_m1__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/tui.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_m1__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/tui.ts:1 */
}

static void sc_f__x25_init_2(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/tui.ts:1 */
  bool sc_t0 = sc_g_e__x25_loaded;
  if (sc_t0) {
    return; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/tui.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_e__x25_loaded = sc_t1; /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/tui.ts:1 */
  sc_f__x25_init_0(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/tui.ts:1 */
  sc_f__x25_init_1(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/tui.ts:2 */
}

static void sc_f__x25_main(void) { /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/tui.ts:1 */
  sc_f__x25_init_2(); /* /data/user/0/com.ai.assistance.operit/files/workspace/0989ed71-87e4-413f-ad5d-c239ed0ee1fa/zfull/entries/tui.ts:1 */
}

int main(int argc, char **argv) {
  scr_init();
  scr_error_vts[0].pre = 0; scr_error_vts[0].post = 4; /* Error */
  scr_error_vts[1].pre = 1; scr_error_vts[1].post = 1; /* TypeError */
  scr_error_vts[2].pre = 2; scr_error_vts[2].post = 2; /* RangeError */
  scr_error_vts[3].pre = 3; scr_error_vts[3].post = 3; /* SyntaxError */
  scr_error_vts[4].pre = 4; scr_error_vts[4].post = 4; /* DOMException */
  scr_lib_init(argc, argv);
  sc_f__x25_main();
  /* no refcounted globals */
  return scr_exit_code_hint_get();
}
