export * from "./zod-lite-core.js";
import { ZodFirstPartyTypeKind, ZodIssueCode, ZodError, ZBase, coerce } from "./zod-lite-core.js";
import type { ZodType as ZodTypeT, ZodError as ZodErrorT, ZodIssue as ZodIssueT, RefinementCtx as RefinementCtxT, SafeParseSuccess as SafeParseSuccessT, SafeParseError as SafeParseErrorT, SafeParseResult as SafeParseResultT, ZodRawShape as ZodRawShapeT } from "./zod-lite-core.js";
export type ZodRawShape = ZodRawShapeT;
export declare class z {
    static ZodFirstPartyTypeKind: typeof ZodFirstPartyTypeKind;
    static ZodIssueCode: typeof ZodIssueCode;
    static ZodObject: (shape: ZodRawShapeT) => ZodTypeT<any>;
    static ZodError: typeof ZodError;
    static coerce: typeof coerce;
    static array: (element: ZBase) => ZodTypeT<any[]>;
    static boolean: () => ZodTypeT<boolean>;
    static date: () => ZodTypeT<unknown>;
    static discriminatedUnion: (discriminator: string, options: readonly ZBase[]) => ZodTypeT<any>;
    static enum: (values: readonly string[]) => ZodTypeT<any>;
    static literal: (value: string | number | boolean) => ZodTypeT<any>;
    static never: () => ZodTypeT<never>;
    static number: () => ZodTypeT<number>;
    static object: (shape: ZodRawShape) => ZodTypeT<any>;
    static partialRecord: (keyType: ZBase, valueType?: ZBase) => ZodTypeT<Record<string, any>>;
    static preprocess: (fn: (value: any) => unknown, schema: ZBase) => ZodTypeT<any>;
    static record: (keyType: ZBase, valueType?: ZBase) => ZodTypeT<Record<string, any>>;
    static strictObject: (shape: ZodRawShape) => ZodTypeT<any>;
    static string: () => ZodTypeT<string>;
    static undefined: () => ZodTypeT<unknown>;
    static union: (options: readonly ZBase[]) => ZodTypeT<any>;
    static unknown: () => ZodTypeT<any>;
    static uuid: () => ZodTypeT<string>;
    static zodToJsonSchemaInternal: (schema: ZBase) => Record<string, unknown>;
}
export declare namespace z {
    type ZodType<O = any> = ZodTypeT<O>;
    type ZodTypeAny = ZodTypeT<any>;
    type ZodString = ZodTypeT<string>;
    type ZodNumber = ZodTypeT<number>;
    type ZodBoolean = ZodTypeT<boolean>;
    type ZodObject<T = any> = ZodTypeT<any>;
    type ZodArray<T = any> = ZodTypeT<any[]>;
    type ZodRecord<K = any, V = any> = ZodTypeT<Record<string, any>>;
    type ZodUnion<T = any> = ZodTypeT<any>;
    type ZodDiscriminatedUnion<T = any> = ZodTypeT<any>;
    type ZodOptional<T = any> = ZodTypeT<any>;
    type ZodNullable<T = any> = ZodTypeT<any>;
    type ZodDefault<T = any> = ZodTypeT<any>;
    type ZodCatch<T = any> = ZodTypeT<any>;
    type ZodEffects<T = any, O = any, I = any> = ZodTypeT<any>;
    type ZodTransform = ZodTypeT<any>;
    type ZodPipe<T = any> = ZodTypeT<any>;
    type ZodNonOptional<T = any> = ZodTypeT<any>;
    type ZodLiteral<T = any> = ZodTypeT<any>;
    type ZodEnum<T = any> = ZodTypeT<any>;
    type ZodError<T = any> = ZodErrorT;
    type ZodIssue = ZodIssueT;
    type RefinementCtx = RefinementCtxT;
    type SafeParseSuccess<T = any> = SafeParseSuccessT<T>;
    type SafeParseError<T = any> = SafeParseErrorT<T>;
    type SafeParseResult<T = any> = SafeParseResultT<T>;
    type infer<T extends ZodTypeT> = any;
    type output<T extends ZodTypeT> = any;
    type input<T extends ZodTypeT> = any;
}
